name: Build and Test Java Gradle app

on: [push]

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: "16"
          distribution: "adopt"
          
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Make the Gradle wrapper script executable
        run: chmod +x ./gradlew
        
      - name: Run a build and test
        run: ./gradlew build
